spring:
  config:
    import: optional:classpath:quizup-defaults.yml
  application:
    name: quizup-theme
  profiles:
    default: local

  flyway:
    locations: classpath:db/migration/theme

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

microservice:
  swagger:
    description: QuizUp Theme Module - Quiz Topics and Questions management
  websocket:
    enabled: false

app:
  seed-data:
    enabled: false


