server:
  port: 8086

spring:
  config:
    import: optional:classpath:quizup-local.yml
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/quizup_theme
    username: postgres
    password: postgres

app:
  seed-data:
    enabled: true
