name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    uses: quizup-organization/quizup-reusable-workflows/.github/workflows/service-release.yml@main
    with:
      java-version: "25"
      github-username: ${{ vars.QUIZUP_GITHUB_USERNAME }}
      service-name: theme
    secrets:
      GITHUB_PASSWORD: ${{ secrets.QUIZUP_GITHUB_TOKEN }}

